// ignore: slash_for_doc_comments
/**
 * The file contains the fields for all the classes, subjects and the chapters.
 * It is used when we require chapter names corresponding to particular class and subject.
 * Names of chapters everywhere in app are taken from here only.
 */

var classes = [
  "Class6",
  "Class7",
  "Class8",
  "Class9",
  "Class10",
  "Class11",
  "Class12",
];

var subjects = [
  "Maths",
  "Chemistry",
  "Physics",
  "Biology",
];

var chap = {
  "Class6": {
    "Maths": [
      "Knowing_Our_Numbers",
      "Whole_Numbers",
      "Playing_With_Numbers",
      "Basic_Geometrical_Ideas",
      "Understanding_Elementary_Shapes",
      "Integers",
      "Fractions",
      "Decimals",
      "Data_Handling",
      "Mensuration",
      "Algebra",
      "Ratio_And_Proportion",
      "Symmetry",
      "Practical_Geometry"
    ],
    "Physics": [
      "Motion_And_Measurement_Of_Distances",
      "Light_Shadows_And_Reflections",
      "Electricity_And_Circuits",
      "Fun_With_Magnets",
      "Water",
      "Air_Around_Us",
      "Garbage_In_Garbage_Out"
    ],
    "Chemistry": [
      "Fibre_To_Fabric",
      "Sorting_Materials_Into_Groups",
      "Separation_Of_Substances",
      "Changes_Around_Us",
      "Getting_To_Know_Plants",
      "Body_Movements",
      "The_Living_Organisms_And_Their_Surroundings",
      "Food:_Where_Does_It_Come_From?",
      "Components_Of_Food",
      "Materials:_Metals_And_Non-Metals"
    ],
    "Biology": [
      "No_Chapter",
    ]
  },
    "Class7": {
      "Maths": [
        "Integers",
        "Fractions_And_Decimals",
        "Data_Handling",
        "Simple_Equations",
        "Lines_And_Angles",
        "The_Triangle_And_Its_Properties",
        "Congruence_Of_Triangles",
        "Comparing_Quantities",
        "Rational_Numbers",
        "Practical_Geometry",
        "Perimeter_And_Area",
        "Algebraic_Expressions",
        "Exponents_And_Powers",
        "Symmetry",
        "Visualising_Solid_Shapes"
      ],
      "Physics": [
        "Heat",
        "Motion_And_Time",
        "Electric_Current_And_Its_Effects",
        "Light",
        "Winds_Storms_And_Cyclones"
      ],
      "Chemistry": [
        "Fibre_To_Fabric",
        "Acids_Bases_And_Salts",
        "Physical_And_Chemical_Changes",
        "Weather_Climate_And_Adaptations_Of_Animals_To_Climate",
        "Water:_A_Precious_Resource"
      ],
      "Biology": [
        "Nutrition_In_Plants",
        "Nutrition_In_Animals",
        "Respiration_In_Organisms",
        "Transportation_In_Animals_And_Plants",
        "Reproduction_In_Plants",
        "Forests:_Our_Lifeline",
        "Wastewater_Story"
      ]
  },
  "Class8": {
    "Maths": [
      "Rational_Numbers",
      "Linear_Equations_In_One_Variable",
      "Understanding_Quadrilaterals",
      "Practical_Geometry",
      "Data_Handling",
      "Squares_and_Square_Roots",
      "Cubes_and_Cube_Roots",
      "Comparing_Quantities",
      "Algebraic_Expressions_and_Identities",
      "Visualising_Solid_Shapes",
      "Mensuration",
      "Exponents_and_Powers",
      "Direct_and_Inverse_Proportions",
      "Factorisation",
      "Introduction_to_Graphs",
      "Playing_with_Numbers"
    ],
    "Physics": [
      "Force_And_Pressure",
      "Friction",
      "Sound",
      "Chemical_Effects_Of_Electric_Current",
      "Light",
      "Stars_And_The_Solar_System"
    ],
    "Chemistry": [
      "Synthetic_Fibres_And_Plastics",
      "Materials_Metals_And_Nonmetals",
      "Coal_And_Petroleum",
      "Combustion_And_Flame",
      "Pollution_Of_Air_And_Water"
    ],
    "Biology": [
      "Crop_Production_And_Management",
      "Microorganisms_Friend_And_Foe",
      "Conservation_Of_Plants_And_Animals",
      "Cell_Structure_And_Function",
      "Reproduction_In_Animals",
      "Reaching_The_Age_Of_Adolescence",
      "Force_And_Pressure"
    ]
  },
  "Class9": {
    "Maths": [
      "Number_Systems",
      "Polynomial",
      "Coordinate_Geometry",
      "Linear_Equations_In_Two_Variables",
      "Introduction_to_Euclids_Geometry",
      "Lines_And_Angles",
      "Triangle",
      "Quadrilaterals",
      "Areas_Of_Parallelograms_And_Triangles",
      "Circle",
      "Construction",
      "Herons_Formula",
      "Surface_Areas_and_Volume",
      "Statistic",
      "Probability_",
    ],
    "Physics": [
      "Motion",
      "Force_and_Law_of_Motion",
      "Gravitation_",
      "Work_and_Energy",
      "Sound",
    ],
    "Chemistry": [
      "Matter_in_Our_Surroundings",
      "Is_Matter_Around_Us_Pure?",
      "Atoms_and_Molecules",
      "Structure_of_the_Atoms",
    ],
    "Biology": [
      "Fundamental_Unit_of_Life",
      "Tissues",
      "Diversity_In_Living_Organisms",
      "Why_Do_We_Fall_Ill",
      "Natural_Resources",
      "Improvements_In_Food_Resources"
    ],
  },
  "Class10": {
    "Maths": [
      "Real_Numbers",
      "Polynomials",
      "Pairs_of_Linear_Equations_In_Two_Variables",
      "Quadratic_Equations",
      "Arithmetic_Progressions",
      "Triangles",
      "Coordinate_Geometry",
      "Introduction_To_Trigonometry",
      "Some_Applications_of_Trigonometry",
      "Circles",
      "Constructions",
      "Areas_Related_to_Circles",
      "Surface_Areas_and_Volumes",
      "Statistics",
      "Probability",
    ],
    "Physics": [
      "Light_Reflection_and_Refraction",
      "The_Human_Eye_And_The_Colourful_World",
      "Electricity",
      "Magnetic_Effects_Of_Electric_Current",
      "Sources_Of_Energy",
    ],
    "Chemistry": [
      "Chemical_Reactions_and_Equations",
      "Acids_Bases_and_Salts",
      "Metals_and_Non_metals",
      "Carbon_and_its_Compounds",
      "Periodic_Classification_of_Elements",
    ],
    "Biology": [
      "Life_Processes",
      "Control_and_Coordination",
      "How_do_Organisms_Reproduce",
      "Heredity_and_Evolution",
      "Our_Environment",
      "Sustainable_Management_of_Natural_Resources",
    ],
  },
  "Class11": {
    "Maths": [
      "Sets",
      "Relation_and_Functions",
      "Trigonometric_Functions",
      "Principle_of_Mathematical_Induction",
      "Complex_Numbers_and_Quadratic_Equations",
      "Linear_Inequalities",
      "Permutations_and_Combinations",
      "Binomial_Theorem",
      "Sequences_and_Series",
      "Straight_Lines",
      "Conic_Sections",
      "Introduction_to_Three_Dimensional_Geometry",
      "Limits_and_Derivatives",
      "Mathematical_Reasoning",
      "Statistic_s",
      "Probability__",
    ],
    "Biology": [
      "The_Living_World",
      "Biological_Classification",
      "Plant_Kingdom",
      "Animal_Kingdom",
      "Morphology_of_Flowering_Plants",
      "Anatomy_of_Flowering_Plants",
      "Structural_Organisation_In_Animals",
      "Cell_The_Unit_Of_Life",
      "Biomolecule",
      "Cell_Cycle_and_Cell_Division",
      "Transport_In_Plants",
      "Mineral_Nutrition",
      "Photosynthesis_In_Higher_Plants",
      "Respiration_in_Plants",
      "Plant_Growth_And_Development",
      "Digestion_And_Absorption",
      "Breathing_And_Exchange_Of_Gases",
      "Body_Fluids_And_Circulation",
      "Excretory_Products_And_Their_Elimination",
      "Locomotion_And_Movement",
      "Neural_Control_And_Coordination",
      "Chemical_Coordination_And_Integration",
    ],
    "Chemistry": [
      "Some_Basic_Concepts_of_Chemistry",
      "Structure_Of_The_Atom",
      "Classification_of_Elements_and_Periodicity_in_Properties",
      "Chemical_Bonding_and_Molecular_Structure",
      "States_of_Matter",
      "Thermodynamic",
      "Equilibrium",
      "Redox_Reactions",
      "Hydrogen",
      "The_s_Block_Elements",
      "The_p_Block_Element",
      "Organic_Chemistry_Some_Basic_Principles_and_Techniques",
      "Hydrocarbons",
      "Environmental_Chemistry",
    ],
    "Physics": [
      "Physical_World",
      "Units_and_Measurements",
      "Motion_in_a_Straight_Line",
      "Motion_in_a_Plane",
      "Laws_of_Motion",
      "Work_Energy_and_Power",
      "System_of_Particles_and_Rotational_Motion",
      "Gravitation",
      "Mechanical_Properties_of_Solids",
      "Mechanical_Properties_of_Fluids",
      "Thermal_Properties_of_Matter",
      "Thermodynamics",
      "Kinetic_Theory",
      "Oscillations",
      "Waves",
    ],
  },
  "Class12": {
    "Maths": [
      "Relations_and_Functions",
      "Inverse_Trigonometric_Functions",
      "Matrices",
      "Determinants",
      "Continuity_and_Differentiability",
      "Applications_of_Derivatives",
      "Integrals",
      "Applications_of_Integrals",
      "Differential_Equations",
      "Vector_Algebra",
      "Three_Dimensional_Geometry",
      "Linear_Programming",
      "_Probability",
    ],
    "Biology": [
      "Reproduction_in_Organisms",
      "Sexual_Reproduction_in_Flowering_Plants",
      "Human_Reproduction",
      "Reproductive_Health",
      "Principles_of_Inheritance_and_Variation",
      "Molecular_Basis_of_Inheritance",
      "Evolution",
      "Human_Health_and_Disease",
      "Strategies_for_Enhancement_in_Food_Production",
      "Microbes_in_Human_Welfare",
      "Biotechnology_Principles_and_Processes",
      "Biotechnology_and_its_Applications",
      "Organisms_and_Populations",
      "Ecosystem",
      "Biodiversity_and_Conservation",
      "Environmental_Issue",
    ],
    "Chemistry": [
      "The_Solid_State",
      "Solutions",
      "ElectroChemistry",
      "Chemical_Kinetics",
      "Surface_Chemistry",
      "General_Principles_and_Processes_of_Isolation_of_Elements",
      "The_p_Block_Elements",
      "The_d_Block_and_f_Block_Elements",
      "Coordination_Compounds",
      "Haloalkanes_and_Haloarenes",
      "Alcohols_Phenols_and_Ethers",
      "Aldehydes_Ketones_and_Carboxylic_Acids",
      "Amines",
      "Biomolecules",
      "Polymers",
      "Chemistry_in_Everyday_Life",
    ],
    "Physics": [
      "Electric_Charges_and_Field",
      "Electrostatic_Potential_and_Capacitance",
      "Current_Electricity",
      "Moving_charges_and_Magnetism",
      "Magnetism_and_Matter",
      "Electromagnetic_Induction",
      "Alternating_Current",
      "Electromagnetic_Waves",
      "Ray_Optics_and_Optical_Instruments",
      "Wave_Optics",
      "Dual_nature_of_radiation_and_matter",
      "Atoms",
      "Nuclei",
      "Semiconductor_Electronics_Materials_Devices_and_Simple_Circuits",
    ],
  }
};
